# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-DBIC
version:      0.09
version_from: lib/Catalyst/Model/DBIC.pm
installdirs:  site
requires:
    Catalyst:                      5.00
    DBIx::Class:                   0
    DBIx::Class::Loader:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
